### ISSUE TITLE
Here is no source code for the game

### ISSUE THREAD

**Issue by tigertv** [DGCProductions/XTREME-Cube#7]
As title says. 

PS. No game in the repo.

**Comment by DGC9Crew** [comment]
I don't understand what you are trying to imply. 

1. Are you saying there is actually no game? 

2. Are judging how my game is so poorly made and so empty in thought that it shouldn't be even declared a game? 

If it's the first option, I have the actual program in a .zip file in the [releases](https://github.com/DGCProductions/XTREME-Cube/releases) section of my repository 😄 

If it is the second option, sorry for you to think that 😟. I am trying my best to make this program the best I can make it 😃.

**Comment by tigertv** [comment]
I mean that 

install_java_pls.java

public class Main {
  public static void main(String [] args) {
    System.out.println("INSTALL JAVA TO RUN PROGRAM!!!");
  }

It's not a game. And here is no any code more.
I'm not judging you about your game. Source code of the game is not here.
Is it proprietary software?

**Comment by DGC9Crew** [comment]
@tigertv Oh install_java_pls.java is not the game, I just made it so it would detect my program as written in Java. I put the actual software (.exe, etc.) in the releases section.

**Comment by tigertv** [comment]
OK. I change the title of the issue.

**Comment by DGC9Crew** [comment]
The game is no longer proprietary and is now open-sourced.
